version = 1

[[annotations]]
path = [
".pylintrc",
".vscode/settings.json",
".python-version",
".devcontainer/devcontainer.json",
".github/workflows/release.yml",
"CHANGELOG.md"
]
SPDX-FileCopyrightText = "2025 Aaron White <w531t4@gmail.com>"
SPDX-License-Identifier = "MIT"
